# Generated by Django 3.2.4 on 2021-06-19 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20210619_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Distributed and Cloud-Based Storage Systems', max_length=128, validators=[django.core.validators.RegexValidator(code='course-name', message='Course name can only contain alphanumeric and space characters.', regex='^([0-9a-zA-Z]+\\s{0,1})*$')])),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='txt',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', max_length=4096),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='The Design and Implementation of a Log-Structured File System', max_length=128, validators=[django.core.validators.RegexValidator(code='paper-title', message='Paper title can only contain alphanumeric and space characters.', regex='^([0-9a-zA-Z]+\\s{0,1})*$')]),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Fall 2021', max_length=128, validators=[django.core.validators.RegexValidator(code='semester-name', message='Semester can only contain alphanumeric and space characters.', regex='^([0-9a-zA-Z]+\\s{0,1})*$')])),
                ('courses', models.ManyToManyField(to='research.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='papers',
            field=models.ManyToManyField(to='research.Paper'),
        ),
    ]
