# Generated by Django 3.2.4 on 2021-06-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20210619_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_number',
        ),
    ]
