# Generated by Django 3.2.4 on 2021-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20210619_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='papers',
            field=models.ManyToManyField(blank=True, to='research.Paper'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, to='research.Course'),
        ),
    ]
